# Generated by Django 4.1.1 on 2022-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carusel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruselmodel',
            name='carusel_css',
            field=models.CharField(default='♥', max_length=200, null=True, verbose_name='Css style'),
        ),
    ]
