# Generated by Django 4.1.1 on 2022-09-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_statusorder_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Text')),
                ('comment_dt', models.DateTimeField(auto_now=True, verbose_name='Time')),
                ('comment_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.order', verbose_name='application')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
